apiVersion: v1
kind: Pod
metadata:
  name: hello-app
spec:
  containers:
  - name: hello-app
    image: devchloe/hello-app:1.0
    ports:
      - containerPort: 3000
    env:
      - name: STUDENT_NAME
        value: 설희관
      - name: GREETING
        value: Hello I'm $(STUDENT_NAME)
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits:
        memory: 128Mi
        cpu: 500m