apiVersion: v1
kind: Pod
metadata:
  name: green-app
  labels:
    group: nature
spec:
  containers:
  - name: green-app
    image: yoonjeong/green-app:1.0
    ports:
    - containerPort: 8081
    resources:
      limits:
        memory: 64Mi
        cpu: 250m