apiVersion: v1
kind: Pod
metadata:
  name: red-app
  labels:
    group: nature
spec:
  containers:
  - name: red-app
    image: yoonjeong/red-app:1.0
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: 64Mi
        cpu: 250m