apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    service: delivery
  namespace: fancy-snackbar
spec:
  type: ClusterIP
  selector:
    service: delivery
  ports:
  - port: 80
    targetPort: 8080