apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    service: order
  namespace: snackbar
spec:
  type: NodePort
  selector:
    service: order
  ports:
  - port: 80
    targetPort: 8080