apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: snackbar
  labels:
    service: payment
spec:
  type: ClusterIP
  selector:
    service: payment
  ports:
  - port: 80
    targetPort: 8080
