apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    service: delivery
  namespace: fancy-snackbar
spec:
  replicas: 2
  selector:
    matchLabels:
      service: delivery
  template:
    metadata:
      labels:
        service: delivery
    spec:
      containers:
      - name: delivery
        image: yoonjeong/my-app:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 64Mi
            cpu: 50m