apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    service: order
  namespace: snackbar
spec:
  replicas: 2
  selector:
    matchLabels:
      service: order
  template:
    metadata:
      labels:
        service: order
    spec:
      containers:
      - name: order
        image: yoonjeong/order:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 64Mi
            cpu: 50m