apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
  namespace: snackbar
spec:
  replicas: 2
  selector:
    matchLabels:
      service: payment
  template:
    metadata:
      labels:
        service: payment
    spec:
      containers:
      - name: payment
        image: yoonjeong/payment:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 64Mi
            cpu: 50m