apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    group: greeting
spec:
  containers:
  - name: hello-app
    image: yoonjeong/hello-app:1.0
    ports:
      - containerPort: 8080
    resources:
      limits:
        memory: 64Mi
        cpu: 250m
