apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-rs
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: yoonjeong/my-app:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 64Mi
            cpu: 250m